name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  issues: write
  discussions: write
  statuses: write
  pull-requests: write
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Prettier
        run: pnpm prettier:check

      - name: Linting
        run: pnpm lint

      - name: Typecheck
        run: pnpm type-check

      - name: Test
        run: pnpm test

      - name: Build app
        run: pnpm build
